workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
        - if: $CI_PIPELINE_SOURCE == "schedule"
        - if: $CI_PIPELINE_SOURCE == "push"
        # Allow run using the Run pipeline button
        - if: $CI_PIPELINE_SOURCE == "web"
        - if: $CI_COMMIT_TITLE =~ /skip-ci$/
          when: never

stages:
    - build
    - deploy

hugo_build:
    image: klakegg/hugo:ext-alpine-ci
    stage: build
    before_script:
        - apk add gzip brotli
    script:
        - hugo --minify -v --gc
        - | 
            find public -type f \( -name '*.html' -o -name '*.js' -o -name '*.css' -o -name '*.xml' -o -name '*.svg' \) \
            -exec /bin/sh -c 'brotli -q 11 -o "$1.br" "$1"' /bin/sh {} \;
        - |
            find public -type f \( -name '*.html' -o -name '*.js' -o -name '*.css' -o -name '*.xml' -o -name '*.svg' \) \
            -exec /bin/sh -c 'gzip -v -f -9 -c "$1" > "$1.gz"' /bin/sh {} \;
    artifacts:
        paths:
            - public
        expire_in: 4 days

Deploy:
    stage: deploy
    needs:
        - hugo_build
    image: alpine:latest
    before_script:
        - apk add openssh rsync
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh-add <(echo "$SSH_KEY")
        - echo "$SSH_KEY" > ~/.ssh/id_key
    script:
        - rsync -avuzh -e "ssh -p ${SSH_PORT} -i ~/.ssh/id_key" public/ $SSH_SERVER --delete
    environment:
        name: Main website
        url: https://fariszr.com
    only:
        - main
