baseURL: https://fariszr.com
title: FarisZR

module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: overrides
      disable: false
    - path: github.com/FarisZR/Hugo-stack-no-cdn
      disable: false
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

DefaultContentLanguage: en

languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1
    params:
      description: Personal blog!, I write about tech, infrastructure and the occasional personal opinion.
      sidebar:
        subtitle: working on aosus.org,
          Founder of ARhackintosh.
          If you want change, be the first one to do it.
        avatar:
          local: true
          src: images/profile.webp
      author:
        name: FarisZR
      copyright: All rights reserved
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: My Projects
          url: /projects
          weight: 2
          params:
            icon: grid

        - identifier: about
          name: About
          url: /about
          weight: 3
          params:
            icon: user

        - identifier: search
          name: Search
          url: /search
          weight: 4
          params:
            icon: search

        - identifier: archives
          name: Archives
          url: /archives
          weight: 5
          params:
            icon: archives

      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/fareszr
          weight: 1
          params:
            icon: brand-twitter

        - identifier: github
          name: GitHub
          url: https://github.com/FarisZR
          weight: 2
          params:
            icon: brand-github

        - identifier: Linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/fariszr/
          weight: 3
          params:
            icon: linkedin

        - identifier: gitlab
          name: GitLab
          url: https://gitlab.com/FarisZR
          weight: 4
          params:
            icon: gitlab

        - identifier: RSS
          name: RSS
          url: https://fariszr.com/en/index.xml
          weight: 5
          params:
            icon: rss

  ar:
    languagedirection: rtl
    languageName: العربية
    languageCode: ar-sa
    weight: 2
    params:
      description: مدونتي, انشر فيها مواضيع عن التقنية والبنية التحتية, بالاضافة الى ارائي الشخصية. 
      sidebar:
        subtitle: اعمل على مجتمع أسس,
          مؤسس هاكنتوش بالعربي.
          اذا كنت تريد التغيير، فكن اول مساهم فيه.
        avatar:
          local: true
          src: images/profile.webp
      author:
        name: FarisZR
      copyright: كافة الحقوق محفوظة
    menu:
      main:
        - identifier: home
          name: الرئيسية
          url: /ar
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: مشاريعي
          url: /ar/projects
          weight: 2
          params:
            icon: grid

        - identifier: about
          name: عني
          url: /ar/about
          weight: 3
          params:
            icon: user

        - identifier: Archives
          name: الأرشيف
          url: /ar/archives
          weight: 4
          params:
            icon: archives

        - identifier: search
          name: بحث
          url: /ar/search
          weight: 5
          params:
            icon: search

      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/fareszr
          weight: 1
          params:
            icon: brand-twitter

        - identifier: github
          name: GitHub
          url: https://github.com/FarisZR
          weight: 2
          params:
            icon: brand-github

        - identifier: Linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/fariszr/
          weight: 3
          params:
            icon: linkedin

        - identifier: gitlab
          name: GitLab
          url: https://gitlab.com/FarisZR
          weight: 4
          params:
            icon: gitlab

        - identifier: RSS
          name: RSS
          url: https://fariszr.com/index.xml
          weight: 5
          params:
            icon: rss

    related:
      includeNewer: true
      threshold: 60
      toLower: false
      indices:
        - name: وسوم
          weight: 100
        - name: اقسام
          weight: 200



permalinks:
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: /favicon.webp

  footer:
    since: 2022
    customText: FarisZR

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: false
      # default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site: fareszr

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: true
      src: images/preview.jpeg

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

  comments:
      enabled: true
      provider: giscus

      giscus:
        repo: FarisZR/FarisZR.com
        repoID: R_kgDOHyxZfA
        category: Comments
        categoryID: DIC_kwDOHyxZfM4CQtrc
        mapping: title
        lightTheme: light
        darkTheme: dark
        reactionsEnabled: 1
        emitMetadata: 0

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

frontmatter:
  dateFormat:
  - date
  - lastmod
  - :git
  lastmod:
  - :git
  - lastmod
  - date

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
