baseURL: https://fariszr.com
languageCode: ar-SA
title: FarisZR

module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: overrides
      disable: false
    - path: github.com/FarisZR/Hugo-stack-no-cdn
      disable: false
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

DefaultContentLanguage: ar

languages:
  ar:
    languagedirection: rtl
    languageName: العربية
    # title: مدونتي
    # contentDir: content/arabic
    weight: 1
    description: مدونتي, انشر فيها مواضيع عن التقنية والبنية التحتية, بالاضافة الى ارائي الشخصية. 
    sidebar:
      subtitle: المدير التقني في مجتمع أسس,
        مؤسس هاكنتوش بالعربي.
        اذا كنت تريد التغيير، فكن اول مساهم فيه.
      avatar:
        local: true
        src: images/profile.webp

    menu:
      main:
        - identifier: home
          name: الرئيسية
          url: /
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: مشاريعي
          url: /projects
          weight: 2
          params:
            icon: grid

        - identifier: about
          name: عني
          url: /about
          weight: 3
          params:
            icon: user

        - identifier: Archives
          name: الأرشيف
          url: /archives
          weight: 4
          params:
            icon: archives

        - identifier: search
          name: بحث
          url: /search
          weight: 5
          params:
            icon: search

      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/fareszr
          weight: 1
          params:
            icon: brand-twitter

        - identifier: gitlab
          name: GitLab
          url: https://gitlab.com/FarisZR
          weight: 2
          params:
            icon: gitlab

        - identifier: github
          name: GitHub
          url: https://github.com/FarisZR
          weight: 3
          params:
            icon: brand-github

        - identifier: codeberg
          name: Codeberg
          url: https://codeberg.org/FarisZR
          weight: 4
          params:
            icon: codeberg

    related:
      includeNewer: true
      threshold: 60
      toLower: false
      indices:
        - name: وسوم
          weight: 100
        - name: اقسام
          weight: 200

  en:
    languageName: English
    description: Personal blog!, I write about tech, infrastructure and the occasional personal opinion.
    sidebar:
      subtitle: Tecnical Director at Aosus,
        Founder of ARhackintosh.
        If you want change, be the first one to do it.
      avatar:
        local: false
        src: /profile.webp
    weight: 2

    menu:
      main:
        - identifier: home
          name: Home
          url: /en
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: My Projects
          url: /en/projects
          weight: 2
          params:
            icon: grid

        - identifier: about
          name: About
          url: /en/about
          weight: 3
          params:
            icon: user

        - identifier: search
          name: Search
          url: /en/search
          weight: 4
          params:
            icon: search

        - identifier: archives
          name: Archives
          url: /en/archives
          weight: 5
          params:
            icon: archives

      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/fareszr
          weight: 1
          params:
            icon: brand-twitter

        - identifier: gitlab
          name: GitLab
          url: https://gitlab.com/FarisZR
          weight: 2
          params:
            icon: gitlab

        - identifier: github
          name: GitHub
          url: https://github.com/FarisZR
          weight: 3
          params:
            icon: brand-github

        - identifier: codeberg
          name: Codeberg
          url: https://codeberg.org/FarisZR
          weight: 4
          params:
            icon: codeberg

permalinks:
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: /favicon.webp

  footer:
    since: 2022
    customText: FarisZR

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: false
      # default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site: fareszr

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: true
      src: images/preview.jpeg

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

  comments:
      enabled: true
      provider: giscus

      giscus:
        repo: FarisZR/comments
        repoID: R_kgDOHyxZfA
        category: Comments
        categoryID: DIC_kwDOHyxZfM4CQtrc
        mapping: title
        lightTheme: light
        darkTheme: dark
        reactionsEnabled: 1
        emitMetadata: 0

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
